CREATE TABLE users (
    `ID` int ( 32 ) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `USERNAME` VARCHAR (32) NOT NULL,
    `EMAIL` VARCHAR (32) NOT NULL,
    `PASSWORD` TEXT NOT NULL,
    `TOKEN` VARCHAR (32) NOT NULL,
    `STATUS` int (32) NOT NULL DEFAULT 0
);